import { FoodItem, Recipe } from './types';

export const mockFoodItems: FoodItem[] = [
  {
    id: '1',
    name: 'Whole Milk',
    category: 'Milk & Dairy',
    quantity: '1 liter',
    expiryDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Fridge',
    dateAdded: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'Opened 3 days ago',
  },
  {
    id: '2',
    name: 'Fresh Spinach',
    category: 'Vegetables & Fruits',
    quantity: '250g',
    expiryDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Fridge',
    dateAdded: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: '3',
    name: 'Chicken Breast',
    category: 'Meat & Protein',
    quantity: '500g',
    expiryDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Fridge',
    dateAdded: new Date().toISOString().split('T')[0],
  },
  {
    id: '4',
    name: 'Brown Rice',
    category: 'Grains & Cereals',
    quantity: '1kg',
    expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Pantry',
    dateAdded: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: '5',
    name: 'Greek Yogurt',
    category: 'Milk & Dairy',
    quantity: '500g',
    expiryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Fridge',
    dateAdded: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: '6',
    name: 'Tomatoes',
    category: 'Vegetables & Fruits',
    quantity: '6 pieces',
    expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Pantry',
    dateAdded: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: '7',
    name: 'Cheddar Cheese',
    category: 'Milk & Dairy',
    quantity: '200g',
    expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Fridge',
    dateAdded: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: '8',
    name: 'Banana',
    category: 'Vegetables & Fruits',
    quantity: '5 pieces',
    expiryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Pantry',
    dateAdded: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: '9',
    name: 'Orange Juice',
    category: 'Beverages',
    quantity: '1 liter',
    expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Fridge',
    dateAdded: new Date().toISOString().split('T')[0],
  },
  {
    id: '10',
    name: 'Whole Wheat Bread',
    category: 'Grains & Cereals',
    quantity: '1 loaf',
    expiryDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    storage: 'Pantry',
    dateAdded: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
];

export const mockRecipes: Recipe[] = [
  {
    id: 'r1',
    name: 'Spinach & Cheese Omelette',
    description: 'A protein-rich breakfast with fresh spinach and melted cheese',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    calories: 320,
    protein: 24,
    carbs: 6,
    fats: 22,
    mealType: 'breakfast',
    cuisine: 'American',
    dietTypes: ['balanced', 'protein_rich', 'keto', 'low_carb', 'vegetarian', 'gluten_free'],
    ingredients: [
      { name: 'Fresh Spinach', quantity: '50', unit: 'g' },
      { name: 'Cheddar Cheese', quantity: '50', unit: 'g' },
      { name: 'Eggs', quantity: '4', unit: 'pieces' },
      { name: 'Butter', quantity: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Beat the eggs in a bowl',
      'Chop spinach finely',
      'Heat butter in a pan',
      'Pour eggs and add spinach',
      'Add cheese and fold omelette',
      'Serve hot',
    ],
  },
  {
    id: 'r2',
    name: 'Grilled Chicken with Brown Rice',
    description: 'A balanced meal with lean protein and complex carbs',
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    calories: 480,
    protein: 42,
    carbs: 48,
    fats: 12,
    mealType: 'lunch',
    cuisine: 'American',
    dietTypes: ['balanced', 'protein_rich', 'mediterranean', 'dash', 'gluten_free', 'paleo', 'whole30'],
    ingredients: [
      { name: 'Chicken Breast', quantity: '300', unit: 'g' },
      { name: 'Brown Rice', quantity: '150', unit: 'g' },
      { name: 'Olive Oil', quantity: '1', unit: 'tbsp' },
      { name: 'Garlic', quantity: '2', unit: 'cloves' },
    ],
    instructions: [
      'Season chicken with salt and pepper',
      'Grill chicken for 6-7 minutes each side',
      'Cook brown rice according to package',
      'Sauté garlic in olive oil',
      'Serve chicken over rice',
    ],
  },
  {
    id: 'r3',
    name: 'Greek Yogurt Banana Bowl',
    description: 'Quick and healthy breakfast with natural sweetness',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 280,
    protein: 18,
    carbs: 42,
    fats: 6,
    mealType: 'breakfast',
    cuisine: 'Greek',
    dietTypes: ['balanced', 'vegetarian', 'mediterranean'],
    ingredients: [
      { name: 'Greek Yogurt', quantity: '200', unit: 'g' },
      { name: 'Banana', quantity: '1', unit: 'piece' },
      { name: 'Honey', quantity: '1', unit: 'tbsp' },
      { name: 'Granola', quantity: '30', unit: 'g' },
    ],
    instructions: [
      'Add yogurt to a bowl',
      'Slice banana on top',
      'Drizzle honey',
      'Sprinkle granola',
      'Enjoy immediately',
    ],
  },
  {
    id: 'r4',
    name: 'Tomato & Cheese Toast',
    description: 'Simple and delicious snack',
    prepTime: 3,
    cookTime: 5,
    servings: 2,
    calories: 240,
    protein: 12,
    carbs: 28,
    fats: 10,
    mealType: 'snack',
    cuisine: 'Italian',
    dietTypes: ['balanced', 'vegetarian', 'mediterranean'],
    ingredients: [
      { name: 'Whole Wheat Bread', quantity: '2', unit: 'slices' },
      { name: 'Tomatoes', quantity: '1', unit: 'piece' },
      { name: 'Cheddar Cheese', quantity: '50', unit: 'g' },
    ],
    instructions: [
      'Toast the bread',
      'Slice tomatoes thinly',
      'Layer tomatoes on toast',
      'Add cheese slices',
      'Broil until cheese melts',
    ],
  },
  {
    id: 'r5',
    name: 'Spinach Chicken Stir Fry',
    description: 'Quick dinner using expiring ingredients',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 380,
    protein: 38,
    carbs: 18,
    fats: 18,
    mealType: 'dinner',
    cuisine: 'Chinese',
    dietTypes: ['balanced', 'protein_rich', 'low_carb', 'keto', 'paleo', 'whole30', 'gluten_free'],
    ingredients: [
      { name: 'Chicken Breast', quantity: '250', unit: 'g' },
      { name: 'Fresh Spinach', quantity: '150', unit: 'g' },
      { name: 'Olive Oil', quantity: '2', unit: 'tbsp' },
      { name: 'Soy Sauce', quantity: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Cut chicken into strips',
      'Heat oil in wok',
      'Stir fry chicken until golden',
      'Add spinach and soy sauce',
      'Cook until spinach wilts',
      'Serve hot',
    ],
  },
  {
    id: 'r6',
    name: 'Vegetable Sushi Rolls',
    description: 'Fresh vegan sushi with avocado and cucumber',
    prepTime: 20,
    cookTime: 0,
    servings: 2,
    calories: 320,
    protein: 8,
    carbs: 62,
    fats: 6,
    mealType: 'lunch',
    cuisine: 'Japanese',
    dietTypes: ['vegan', 'vegetarian', 'balanced', 'dash'],
    ingredients: [
      { name: 'Sushi Rice', quantity: '200', unit: 'g' },
      { name: 'Nori Sheets', quantity: '4', unit: 'pieces' },
      { name: 'Avocado', quantity: '1', unit: 'piece' },
      { name: 'Cucumber', quantity: '1', unit: 'piece' },
    ],
    instructions: [
      'Cook and cool sushi rice',
      'Place nori on bamboo mat',
      'Spread rice on nori',
      'Add avocado and cucumber strips',
      'Roll tightly and slice',
      'Serve with soy sauce',
    ],
  },
  {
    id: 'r7',
    name: 'Lentil Dal',
    description: 'Hearty Indian vegan curry with protein-rich lentils',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    calories: 280,
    protein: 16,
    carbs: 44,
    fats: 4,
    mealType: 'dinner',
    cuisine: 'Indian',
    dietTypes: ['vegan', 'vegetarian', 'gluten_free', 'dash', 'whole30'],
    ingredients: [
      { name: 'Red Lentils', quantity: '200', unit: 'g' },
      { name: 'Tomatoes', quantity: '2', unit: 'pieces' },
      { name: 'Onion', quantity: '1', unit: 'piece' },
      { name: 'Curry Powder', quantity: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Sauté onions until golden',
      'Add tomatoes and spices',
      'Add lentils and water',
      'Simmer for 25 minutes',
      'Season to taste',
      'Serve with rice',
    ],
  },
  {
    id: 'r8',
    name: 'Paleo Breakfast Bowl',
    description: 'Grain-free breakfast with eggs and vegetables',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 380,
    protein: 28,
    carbs: 12,
    fats: 26,
    mealType: 'breakfast',
    cuisine: 'American',
    dietTypes: ['paleo', 'whole30', 'keto', 'low_carb', 'gluten_free'],
    ingredients: [
      { name: 'Eggs', quantity: '4', unit: 'pieces' },
      { name: 'Sweet Potato', quantity: '150', unit: 'g' },
      { name: 'Avocado', quantity: '1', unit: 'piece' },
      { name: 'Spinach', quantity: '50', unit: 'g' },
    ],
    instructions: [
      'Dice and roast sweet potato',
      'Scramble eggs',
      'Sauté spinach',
      'Arrange in bowl',
      'Top with avocado slices',
      'Season and serve',
    ],
  },
];

export const categories = [
  'Milk & Dairy',
  'Vegetables & Fruits',
  'Grains & Cereals',
  'Meat & Protein',
  'Beverages',
  'Condiments & Sauces',
  'Snacks',
  'Others',
];

export const storageLocations = ['Fridge', 'Freezer', 'Pantry', 'Cupboard'];
